### ISSUE TITLE
iOS NavigationPage is gone when xaml reloaded

### ISSUE THREAD

**Issue by agusibrahim** [ylatuya/XAMLator#14]
when i making changes to xaml file, NavigationPage is gone. btw i am using prism for mvvm. your tools is awesome, but please fix it. i attached screenshot before and after making changes
![simulator screen shot - iphone 8 - 2018-11-05 at 09 59 12](https://user-images.githubusercontent.com/5948377/47975750-a973c480-e0e1-11e8-8c1f-0738f877c41d.png)
![simulator screen shot - iphone 8 - 2018-11-05 at 09 59 28](https://user-images.githubusercontent.com/5948377/47975751-aa0c5b00-e0e1-11e8-83e2-8c4de2b38920.png)

**Comment by ylatuya** [comment]
I have updated the docs explaining why it's happening an how to fix it:
https://github.com/ylatuya/XAMLator/blob/master/README.md#customization
