### ISSUE TITLE
Cannot update xaml that uses other xaml files

### ISSUE THREAD

**Issue by ChasakisD** [ylatuya/XAMLator#20]
### Description

When the xaml references references other xaml files starts to allocate/deallocate memory and after some seconds it breaks. That said tho, that only happens when you made a change and you save. The first time works perfectly.  Because the log is too big (18k lines), i uploaded it and added a link. Later, I'll add a repro link.

### Steps to Reproduce

1. Create a ```Grid``` in another xaml file, add some dummy text and some bindable properties.
2. Create a page with a ```Stacklayout``` and reference the ```Grid``` that has been previously created.
3. Start the app.
4. Made a minor change to the Page and save.

### Expected Behavior

The xaml page should be updated as expected.

### Actual Behavior

The app freezes for about 10-15 seconds and then crashes.

### Logs

https://goo.gl/qMsVYA

**Comment by ylatuya** [comment]
Could you please attach the 2 XAML files so i can have an easier way to reproduce it? Looking at the logs it looks like a infinite parsing loop.

**Comment by ChasakisD** [comment]
TestView.xaml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentView 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    x:Class="TestApp.CustomViews.TestView"
    x:Name="ThisTestView">
    <Label Text="Welcome From TestView" BackgroundColor="{Binding Source={x:Reference ThisTestView}, Path=TestColor}"/>
</ContentView>
```

TestView.xaml.cs
```cs
using Xamarin.Forms;

namespace TestApp.CustomViews
{
    public partial class TestView
    {
        #region Bindable Properties

        public static readonly BindableProperty TestColorProperty = BindableProperty.Create(
            nameof(TestColor), typeof(Color), typeof(TestView), Color.Wheat);

        public Color TestColor
        {
            get => (Color) GetValue(TestColorProperty);
            set => SetValue(TestColorProperty, value);
        }

        #endregion
        
        public TestView()
        {
            InitializeComponent();
        }
    }
}
```

TestPage.xaml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:customViews="clr-namespace:TestApp.CustomViews;assembly=TestApp"
    x:Class="TestApp.Views.TestPage">
    <StackLayout>
        <Label Text="Welcome From TestPage" />
        
        <customViews:TestView TestColor="Red" /> 
    </StackLayout>
</ContentPage>

```

**Comment by ylatuya** [comment]
Thanks! This used to work before, it should be easy to fix :)

**Comment by ylatuya** [comment]
This fix requires an update in both the addin and the nuget, I will publish both now

**Comment by ChasakisD** [comment]
@ylatuya Thank you! Appreciated your effort!
