### ISSUE TITLE
Stuck on evaluation error

### ISSUE THREAD

**Issue by ChasakisD** [ylatuya/XAMLator#23]
### Description

Some times (it happens randomly or when there are a lot of files open and you switch on them) the PreviewPage stucks on Evaluation Error: Class, struct or interface method must have a return type. Trying switching to a cs file and back to a xaml one does not fix the issue.

Some times the output prints some gc info and seems that it got the change and trying to preview the file(with no success) and other ones it just does nothing. You have to re-run the application to make it work. 

Haven't tried to make a toolbaritem for start and end(if it exists) the preview via an abstraction. Maybe a button on the preview page, like hard reload would resolve this issue.

### Expected Behavior

The preview page should detect the focused page on the IDE and display it correctly.

### Actual Behavior

The preview page after some time of switching files it gets stuck and does not preview the file.

**Comment by ylatuya** [comment]
Thanks again for you report :) I believe a hard reset option would be useful. Could you please attach some logs next time it happens so I can try to guess what happens to provide the correct fix?

**Comment by KarolStosik** [comment]
I have this error after any change to xaml. Where can I get the logs from?

**Comment by ylatuya** [comment]
I have this error fixed already. I have quite busy these days, I just needs to find time to publish a new release :)

**Comment by ylatuya** [comment]
A new release is available, you will have to update both the Add-in and the NuGet package :)
