### ISSUE TITLE
The reason behind choosing Target framework v4.7

### ISSUE THREAD

**Issue by yasmoradi** [ylatuya/XAMLator#25]
Most projects use .net 4.6.1 sdk as it's the minimum version of .net framework which supports .net standard 2.0
But I can't understand the benefit of choosing .net 4.7
It also prevents people from building project with their visual studio unless they install 4.7 sdk.
Note that 4.6.1 sdk is installed by default.
I'm open to change those configurations and make project built.
I'm willing to help with removing packages.config files too.

**Comment by ylatuya** [comment]
There is no point actually, on the client the minimum requirements are set by Xamarin.Forms, and it's netstandard 2.0, and on the server net461 should be fine too, so feel free to change it.
The reason there isn't a unique library targeting netstandard 2.0 for all platforms is that we have a dependency with Mono.CSharp for the evaluator. I started working on a new implementation that uses the Roslyn API [here](https://github.com/ylatuya/XAMLator/blob/e95a1237a9dacda29b5d9dd40bfb5e6d506a22da/XAMLator.Server/RoslynEvaluator.cs) but it's not working on iOS.

**Comment by yasmoradi** [comment]
It's not working on iOS devices or iOS emulators or both?

**Comment by ylatuya** [comment]
It's not working on both because of https://github.com/dotnet/roslyn/issues/24442

**Comment by yasmoradi** [comment]
I found out why .net 47 was chosen! Before XF 3.3, the minimum version of .net was specified to 47 which is obviously wrong. They've fixed that recently.

So, this is what I recommend:
1- Update to XF 3.3
2- Select net 461 instead of 47. (GTK Forms project itself has this issue too)
3- Multi-target projects, instead of having multiple projects such as XAMLator.Server.Mono.Droid & XAMLator.Server.Mono.iOS. I know .net standard is not a choise because of Mono Evaluator addin. But multi target project has no limiation in this area.
4- Use Package References and new csproj format.

I recommend them because I think we need a better structure to make project growth. By doing that, we can have fewer projects and fewer packages (Now I can build the project using only 13 packages)

We can use Owin instead of the custom HTTP server and we are also able to drop using NuGet.Build.Packaging, dot net sdk can handle that so easily if we move to new csproj format.

**Comment by ylatuya** [comment]
Right, that was the reason, XF required net47

1. Ok
2. Ok
3. Multitarget projects are [not yet supported in vs4mac](https://developercommunity.visualstudio.com/content/problem/62584/vs4mac-not-properly-handling-msbuildsdk-style-proj.html), which is my main development environment, so we have to leave them as they are now.
4. If that works with vs4mac I am ok with it, the CI's run on a macOS host so once you create the PR you will check if it builds correctly or not.

Regarding Owin, the is no HTTP server at all, communication is done with raw TCP sockets and Json serialization, similar to how websockets works. The reason for this is that it has less overhead than HTTP, it keeps the dependencies pretty small (Xamarin.Forms and Json.Net) and it only requires to reverse 1 port in Android's emulator instead of 2.

There isn't NuGet.Build.Packaging either, everything is built with a .nuspec file.

**Comment by yasmoradi** [comment]
> Regarding Owin, the is no HTTP server at all, communication is done with raw TCP sockets and Json serialization, similar to how websockets works.

It's a correct design. But what's [this](https://github.com/ylatuya/XAMLator/blob/master/XAMLator.Core/HttpServer/HttpHost.cs) anyway?

> There isn't NuGet.Build.Packaging either, everything is built with a .nuspec file.

csproj is capable to handle nuget package creation and there is no need for .nuspec file anymore these days. I also found Nuget.Build.Packaging [here](https://github.com/ylatuya/XAMLator/blob/master/XAMLator.Server.Droid/XAMLator.Server.Mono.Droid.csproj#L4)

And about vs4mac, I'll do whatever vs4mac supports, don't worry about that (:

**Comment by ylatuya** [comment]
> > Regarding Owin, the is no HTTP server at all, communication is done with raw TCP sockets and Json serialization, similar to how websockets works.
> 
> It's a correct design. But what's [this](https://github.com/ylatuya/XAMLator/blob/master/XAMLator.Core/HttpServer/HttpHost.cs) anyway?

It's not used anymore, I will remove it from the repo.


> > There isn't NuGet.Build.Packaging either, everything is built with a .nuspec file.
> 
> csproj is capable to handle nuget package creation and there is no need for .nuspec file anymore these days. I also found Nuget.Build.Packaging [here](https://github.com/ylatuya/XAMLator/blob/master/XAMLator.Server.Droid/XAMLator.Server.Mono.Droid.csproj#L4)

It's probably a leftover from my first attempt to automate packaging directly from the csproj. I will clean this too.

Here is the PR for the cleanup: https://github.com/ylatuya/XAMLator/pull/26
