### ISSUE TITLE
cannot find XAMlator in VS 2017 Extensions

### ISSUE THREAD

**Issue by AngeloLazzari** [ylatuya/XAMLator#27]
Hi, i followed the instructions 

Install the XAMLator add-in for VisualStudio for Mac in the Add-in Manager:

Open Visual Studio->Extensions
Search for XAMLator
Install it!

but no way to find the package.. there is some problem?

Thank you very much!
Angelo

**Comment by yasmoradi** [comment]
If you mean vs4mac extension, then it seems that you've found it!
If you mean nuget package, [here](https://www.nuget.org/packages/XAMLator/) it is.
If you mean visual studio extension, it's not ready yet.

**Comment by ylatuya** [comment]
Hi,
Just a line below in the README.md you will find the link to install it while it could be published to the addins manager:
> The Add-in store is down, meanwhile you can install the add-in from the CI build artifact

The add-in repository was down but it seems to be fixed now and I have published the add-in
