### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by BenoistLUGNIER** [ylatuya/XAMLator#29]
It's not working with the startup project
Windows 10 updated
VS 2017 Entreprise 15.8.9
Xamarin : 4.11.0.779
Xamarin.Forms :
- 3.4.0.987044 pre2
- 3.3.0.967583
- 3.3.0.912540

I'd try on real device  galaxy S8+ (oreo 8.0) and chuwi (lollipop)

I'd updated OnCreate Method
The compilation is good,
I'm on debug mode
The deployment is good
The launch is ok
Modifying XAML or XAML.CS (saved of course) - Nothing append on the UI

Thanks

**Comment by jsuarezruiz** [comment]
Hi @BenoistLUGNIER, we are working on the Visual Studio for Windows extension and will include support soon. At the moment, there is an addin for Visual Studio for macOS.

**Comment by ylatuya** [comment]
As documented [here](https://github.com/ylatuya/XAMLator#windows) we are working on a the Visual Studio add-on for Windows.
I will close this as a duplicated of https://github.com/ylatuya/XAMLator/issues/16
