### ISSUE TITLE
[CSS] Including a StyleSheet throws an error on reload

### ISSUE THREAD

**Issue by davidortinau** [ylatuya/XAMLator#3]
Including a CSS file works on the initial run.

Global.css (EmbeddedResource):
```
.superLabel {
    color: black;
    background-color: transparent;
    font-size: 64;
}
```

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:XAMLator.SampleApp"
             x:Class="XAMLator.SampleApp.MainPage">
    
    <ContentPage.Resources>
        <StyleSheet Source="/Global.css"/>
    </ContentPage.Resources>
    
    <StackLayout>
        <!-- Place new controls here -->
        <Label Text="This is my page!"
           TextColor="White"    
           HorizontalOptions="Center"
           BackgroundColor = "Red"
           class="superLabel"
           VerticalOptions="CenterAndExpand" />
    </StackLayout>
</ContentPage>
```

<img width="584" alt="screenshot 2018-09-22 09 36 21" src="https://user-images.githubusercontent.com/41873/45918339-20fbd600-be4b-11e8-8e9f-5fba32908896.png">

However upon hitting save and triggering a reload, XAMLator throws an eval error.

<img width="584" alt="screenshot 2018-09-22 09 38 54" src="https://user-images.githubusercontent.com/41873/45918354-543e6500-be4b-11e8-90ff-b5896cadef6a.png">

**Comment by ylatuya** [comment]
Fixed in https://github.com/ylatuya/XAMLator/pull/10
