### ISSUE TITLE
Not working on macOS target

### ISSUE THREAD

**Issue by pellet** [ylatuya/XAMLator#32]
Steps to reproduce:
1) Remove the XAMLator.Server project dependency from your XAMLator.SampleApp.MacOS project.
2) Add the XAMLator nuget package as a reference.
3) See it can't see the XAMLator namespace and will not compile.

**Comment by ylatuya** [comment]
What target framework are you using? The libraries are build for net47 as Xamarin.Forms before 3.3 was targeting v4.7 (see https://github.com/ylatuya/XAMLator/issues/25 for more details).

**Comment by ylatuya** [comment]
I can reproduce it. I will fix it ASAP

**Comment by ylatuya** [comment]
It should be fixed in the nuget package 2018.11.19.9. You probably have to remove and add the nugget again in your project so the references are added correctly in the csproj

**Comment by pellet** [comment]
im getting this now
```
Target XamlC:
    Compiling Xaml, assembly: obj/x86/Debug/Mac.exe
    Touching "obj/x86/Debug/XamlC.stamp".
Target WeaveXAMLator:
    /Users/belmer/.nuget/packages/xamlator/2018.11.19.9/build/XAMLator.targets(23,9): error MSB4044: The "AssemblyWeaver" task was not given a value for the required parameter "Path".
Done building target "WeaveXAMLator" in project "Mac.csproj" -- FAILED.

Done building project "Mac.csproj" -- FAILED.
```

**Comment by ylatuya** [comment]
It should be finally fixed in the latest nugget with https://github.com/ylatuya/XAMLator/pull/35
