### ISSUE TITLE
[iOS] An evaluation error

### ISSUE THREAD

**Issue by pdamco** [ylatuya/XAMLator#37]
Getting error on iOS 
iOS version 12.1
Xamarin Forms 3.4

Getting Preview Error!
Oh no! An evaluation error!

Below given is the error:

System.NotSupportedException: Specified method is not supported. at Mono.CSharp.Evaluator.ComplileBlock(Mono.CSharp.Class host, Mono.CSharp.Undo undo, Mono.CSharp.Report Report) [0x00060] in /Library/Frameworks/Xamain.iOS.framework/Verions/12.2.1.10/src/Xamrin.iOS/mcs/eval.cs:707

**Comment by ylatuya** [comment]
Hi,
Is this on a real device or the emulator?
This usually happens when the --enable-repl option is not configured correctly. See:
https://github.com/ylatuya/XAMLator#ios-additional-setup

**Comment by pdamco** [comment]
This is on real device. 

--enable-repl is not working for real device.

**Comment by ylatuya** [comment]
XAMLator won't work in iOS devices, only the simulator, because of https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations#no-dynamic-code-generation.
I have updated the README clarifying that it only works on real devices for Android.
