### ISSUE TITLE
Remove MonoDevelop dependencies from Core project

### ISSUE THREAD

**Issue by jsuarezruiz** [ylatuya/XAMLator#4]
I was adding the Visual Studio Windows extension and I found a couple of necessary changes to be able to do it.

We have to remove references to MonoDevelop from the Core project. We can create an IDialog interface (or similar) and implement it in each platform (Windows and macOS).

If you want I can add changes in a PR.

**Comment by ylatuya** [comment]
Right, my mistake :) An IDialog sounds good for that

**Comment by ylatuya** [comment]
This issue is now fixed in master with the new https://github.com/ylatuya/XAMLator/blob/master/XAMLator.Client/IIDE.cs interface.
