### ISSUE TITLE
AssemblyWeaver error

### ISSUE THREAD

**Issue by gaffkins** [ylatuya/XAMLator#40]
Hi, when I try build (clean, new project) on iOS Simulator I got error:
Error MSB4044: The "AssemblyWeaver" task was not given a value for the required parameter "Path". (MSB4044) (XAMLatorTest)

**Comment by ylatuya** [comment]
I will fix it, but it looks only a test issue, the other projects should build correctly and unless you are trying to pass the unit tests it shouldn't affect

**Comment by gaffkins** [comment]
I don't use tests, it is clean project.

**Comment by ylatuya** [comment]
Hi,

Are you using netstandard for the shared code? If so to which project did you add XAMLator, to the shared netstandard project or the application project?

**Comment by gaffkins** [comment]
Hi, yes it's netstandard. I add XAMLator to shared and platforms projects.

**Comment by ylatuya** [comment]
You shouldn't add it the netstandard project, only to the application projects, as described here:
https://github.com/ylatuya/XAMLator#installation

I will make the error more explicit :)

**Comment by gaffkins** [comment]
Ok, its work. My mistake. Thank you and best regards!
