### ISSUE TITLE
A member is already defined

### ISSUE THREAD

**Issue by gaffkins** [ylatuya/XAMLator#41]
The MainPage is work ok, I add next XAML Page and when I try edit it i got error:
Oh no! An evaluation error! 
A memebr XAMLatorTest.TestPAge21.TestPage21() is already exists. Rename this member or use different parameters types.

When I change something on this page the number 21 rise.

**Comment by soydachi** [comment]
This issue raised to me too.
The other page si as normal as the first one, only the FFImageLoader in there.

**Comment by soydachi** [comment]
@gaffkins @ylatuya I think this is a vs for mac issue.

In vs for windows when we are creating an Xamarin Forms ContentPage, we get the `[XamlCompilation(XamlCompilationOptions.Compile)]` markup in the code behind and in the csproj it is able to put this file as a embeddedResource 
`</EmbeddedResource>
     <EmbeddedResource Update="PathToXAML">
        <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
     </EmbeddedResource>`

But in vs for mac this is not working now.

**Comment by ylatuya** [comment]
Hi, today I will find some time to release a new version that fixes several issues and provides better error logs to debug. I hope it fixes this one.

**Comment by ylatuya** [comment]
I uploaded a new version of both the Add-in and the NuGet package, could you try it please?

**Comment by soydachi** [comment]
> I uploaded a new version of both the Add-in and the NuGet package, could you try it please?

Yes of course! I will update it now :)

**Comment by soydachi** [comment]
And of course thank you very mucho!!!
