### ISSUE TITLE
The "AssemblyWeaver" task was not given a value for the required parameter "Path". 

### ISSUE THREAD

**Issue by sethom** [ylatuya/XAMLator#42]
I'm getting this error message after building for iOS simulator:

"The "AssemblyWeaver" task was not given a value for the required parameter "Path". "

 XAMLator is installed in the PCL project and the iOS project with mtouch arguments of: --enable-repl

Thanks!

**Comment by ylatuya** [comment]
Hi, you should only add it to the native project only, not the shared one. Try removing it from the PCL project and it should work :)
https://github.com/ylatuya/XAMLator/blob/master/README.md#installation

**Comment by jsuarezruiz** [comment]
Maybe we should add this to a Faq with frequently asked questions?

**Comment by forlayo** [comment]
I've same issue and I've added it just on native (UWP) project.. should I add any kind of intialization ? there's no instructions for UWP :S
