### ISSUE TITLE
The socket has been shut down

### ISSUE THREAD

**Issue by soydachi** [ylatuya/XAMLator#44]
Hi @ylatuya in the new versión

When I open a xaml file in vs for mac, the xamlator always shows this error:

<img width="340" alt="screenshot 2019-02-20 at 16 23 06" src="https://user-images.githubusercontent.com/1771785/53105211-fb294900-3530-11e9-9fe0-e36b16d0e35b.png">

Versions
vs for mac extension: 1.05
nuget version: 2019.2.20.3

**Comment by ylatuya** [comment]
Thanks for reporting, I have been able to reproduce it finally. I will publish a new release this weekend

**Comment by ylatuya** [comment]
There is a new release available :D
