### ISSUE TITLE
SampleApp.iOS is a namspace but a type was expected

### ISSUE THREAD

**Issue by soydachi** [ylatuya/XAMLator#45]
In all versions I have tested, when I'm in a xaml page and open his code behind c# class, XAMLator loops in an error of namespace type. This error go away only if I reopen vs for mac

![image](https://user-images.githubusercontent.com/1771785/53105529-9ae6d700-3531-11e9-96cf-8e3591866bef.png)

**Comment by ylatuya** [comment]
I believe there is a mismatch between the version deployed in the app and the newest one. Make sure you do a clean rebuild and redeploy to the app the new build :)
