### ISSUE TITLE
Not Working In Mac

### ISSUE THREAD

**Issue by donchakkappan** [ylatuya/XAMLator#47]
XAMLator is not working for me. I am using VS2017 Community edition for Mac.

These are the logs I am getting.

Loaded assembly: XAMLator.Server.dll [External]
[Mono] Image addref XAMLator.Server[0x7c337cdb80] -> XAMLator.Server.dll[0x7c337dd000]: 2
[Mono] Prepared to set up assembly 'XAMLator.Server' (XAMLator.Server.dll)
[Mono] Assembly XAMLator.Server[0x7c337cdb80] added to domain RootDomain, ref_count=1
[Mono] AOT: image 'XAMLator.Server.dll.so' not found: dlopen failed: library "/data/app/-1/lib/arm64/libaot-XAMLator.Server.dll.so" not found
[Mono] AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-arm64-v8a-release/lib/mono/aot-cache/arm64/XAMLator.Server.dll.so' not found: dlopen failed: library "/data/app/-1/lib/arm64/libaot-XAMLator.Server.dll.so" not found

[Mono] Config attempting to parse: 'XAMLator.Server.dll.config'.
[Mono] Config attempting to parse: '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-arm64-v8a-release/etc/mono/assemblies/XAMLator.Server/XAMLator.Server.config'.

[Mono] Assembly Ref addref XAMLator.Server[0x7c337cdb80] -> mscorlib[0x7c473a2480]: 105
[Mono] Assembly Ref addref XAMLator.Server[0x7c337cdb80] -> Xamarin.Forms.Core[0x7c3374ea80]: 25

**Comment by ylatuya** [comment]
The current version was using System.Diagnostics.Debug to print logs, that are removed for Release builds. I will fix it an publish a new version so we can have at least some logs.

**Comment by donchakkappan** [comment]
@ylatuya Thank you so much for your quick reply.I am eagerly waiting to get this working.

**Comment by ylatuya** [comment]
I have published a new version, it will take a bit to be public in nuget.org with debug logs fixed.
Before anything check that:
- The XAMLator visual studio addin is at version 1.0.6
- You have only one instance of visual studio running

The app should print something like:
[1 Info  11:52:05.757] Connecting to IDE at tcp://172.16.15.24:8488

**Comment by donchakkappan** [comment]
@ylatuya I tried it.Still I am getting only the below logs.

AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/mono/aot-cache/arm/**XAMLator.Server.dll.so' not found: dlopen failed**: library "/data/app/com.dev-1/lib/arm/libaot-XAMLator.Server.dll.so" not found

I am using the latest XAMLator builds
<img width="255" alt="screen shot 2019-03-01 at 9 25 20 am" src="https://user-images.githubusercontent.com/6335190/53616444-8927c280-3c08-11e9-98b2-7b4b8f6a8a6f.png">
<img width="309" alt="screen shot 2019-03-01 at 9 26 21 am" src="https://user-images.githubusercontent.com/6335190/53616445-8927c280-3c08-11e9-84e2-93278553f6b6.png">

**Comment by donchakkappan** [comment]
Now I tried using master.Now I am getting 

[Error 14:44:24.515] Couldn't register device at 192.168.43.36
[Warn  14:44:24.538] Caught an exception System.Net.Sockets.SocketException: Connection refused (in `mscorlib')
  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in <3e9b3e26c4694baab3f689687ad40612>:0 
  at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in <3e9b3e26c4694baab3f689687ad40612>:0 
  at System.Net.Sockets.TcpClient.EndConnect (System.IAsyncResult asyncResult) [0x0000c] in <3e9b3e26c4694baab3f689687ad40612>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at XAMLator.TcpCommunicatorClient+<Connect>d__1.MoveNext () [0x000a1] in <1733197bd6f941628dab7d25fd6fab01>:0 
--- End of stack trace from previous location where exception was thrown ---
  at XAMLator.Server.PreviewServer+<RegisterDevice>d__13.MoveNext () [0x000cd] in <1733197bd6f941628dab7d25fd6fab01>:0

**Comment by ylatuya** [comment]
>  AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/mono/aot-cache/arm/**XAMLator.Server.dll.so' not found: dlopen failed**: library "/data/app/com.dev-1/lib/arm/libaot-XAMLator.Server.dll.so" not found

This is not an error, those are just debug prints from mono trying different extensions. After updating the nuget make sure you do a clean rebuild, as sometimes incremental builds don't update correctly dependencies. 

With master make sure you build in release mode, otherwise the connection port is different, this is why you have a connection error.

**Comment by donchakkappan** [comment]
@ylatuya It works like charm...Thanks a lot brother.
